/*
 * This source file was generated by the Gradle 'init' task
 */
package com.argenclima;

import java.util.Scanner;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

public class App {
  public static void main(String[] args) {
    Menu menu = new Menu();
    System.out.println(
        "El siguiente programa permite ver la temperatura promedio de pais/provincia/localidad entre los años 2021-2026");
    menu.mostrarMenu();
  }
}

class Menu {
  private Scanner sc;
  public Pais argentina;
  public Provincia provinciaSeleccionada;
  public Localidad localidad;

  public Menu() {
    this.sc = new Scanner(System.in);
    this.argentina = new Pais("Argentina");
  }

  public void mostrarMenu() {
    int opcion = 0;
    String nombreLugar;

    while (opcion != 5) {
      System.out.println("Elegir una opcion");
      System.out.println("1. Cargar datos");
      System.out.println("2. Buscar pais");
      System.out.println("3. Buscar Provincia");
      System.out.println("4. Buscar Localidad");
      System.out.println("5.Salir");
      opcion = sc.nextInt();
      sc.nextLine();
      switch (opcion) {
        case 1:
          realizarCargaDatos();
          System.out.println("Datos cargados.");
          break;
        case 2:
          opcion = ingresarAnio();
          if (opcion >= 2021 && opcion <= 2026) {
            System.out.println("La temperatura promedio del pais es: " + argentina.temperaturaPromedio(opcion));
          } else {
            System.out.println("No hay información del año correspondiente");
          }
          break;
        case 3:
          System.out.println("Ingrese el nombre de la provincia");
          nombreLugar = ingresarNombreLugar();
          provinciaSeleccionada = argentina.getProvincia(nombreLugar);
          if (provinciaSeleccionada == null) {
            System.out.println("No se encontro esa provincia, revisar si los datos fueron cargados o no existe");
          } else {
            opcion = ingresarAnio();
            if (opcion >= 2021 && opcion <= 2026) {
              System.out.println(
                  "La temperatura promedio de la provincia es: " + provinciaSeleccionada.temperaturaPromedio(opcion));
            } else {
              System.out.println("No hay información del año correspondiente");
            }
          }
          break;
        case 4:
          System.out.println("Ingrese el nombre de la provincia de la localidad");
          nombreLugar = ingresarNombreLugar();
          provinciaSeleccionada = argentina.getProvincia(nombreLugar);
          if (provinciaSeleccionada == null) {
            System.out.println("No se encontro esa provincia, revisar si los datos fueron cargados o no existe");
          } else {
            System.out.println("Ingrese el nombre de la localidad");
            nombreLugar = ingresarNombreLugar();
            localidad = provinciaSeleccionada.getLocalidad(nombreLugar);
            if (localidad == null) {
              System.out.println("No se encontro esa localidad, revisar si los datos fueron cargados o no existe");
            } else {
              opcion = ingresarAnio();
              if (opcion >= 2021 && opcion <= 2026) {
                System.out.println("La temperatura promedio de la localidad es: "
                    + provinciaSeleccionada.getLocalidad(nombreLugar).temperaturaPromedio(opcion));
              } else {
                System.out.println("No hay información del año correspondiente");
              }
            }
          }
          break;
        case 5:
          System.out.println("Gracias por usar");
          break;
        default:
          System.out.println("Opcion invalida");
          break;
      }
    }
  }

  public int ingresarAnio() {
    int anio;
    System.out.println("Ingrese el año entre 2021-2026 para calcular la temperatura promedio");
    anio = sc.nextInt();
    sc.nextLine();
    return anio;
  }

  public String ingresarNombreLugar() {
    String nombreLugar;
    nombreLugar = sc.nextLine();
    return nombreLugar;
  }

  public void realizarCargaDatos() {
    ExecutorService pool = Executors.newFixedThreadPool(8);
    String[] provincias = { "Neuquén", "Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán", "Salta", "Chaco",
        "Formosa", "Jujuy", "La Pampa", "La Rioja", "San Juan", "San Luis", "Santiago del Estero", "Tierra del Fuego",
        "Chubut", "Entre Ríos", "Misiones", "Río Negro", "Catamarca", "Corrientes", "Santa Cruz" };
    for (int i = 0; i < provincias.length; i++) {
      Provincia objetoProvincia = new Provincia(provincias[i]);
      argentina.addProvincia(objetoProvincia);
      pool.execute(new CargadorDatos(objetoProvincia));
    }
    pool.shutdown();
    try {
      pool.awaitTermination(4, TimeUnit.SECONDS);
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
    }
  }
}
